%%{ init: { 'flowchart': { 'curve': 'linear' } } }%%
flowchart BT
    common[Common<br>common]

    si[Static Analysis Infrastructure<br>si]
    bi[Bytecode Infrastructure<br>bi]

    br[Bytecode Representation<br>br]
    da[Bytecode Disassembler<br>da]

    ifds[IFDS<br>ifds]
    ai[Abstract Interpretation Framework<br>ai]
    bc[Bytecode Creator<br>bc]

    tac[Three Address Code<br>tac]
    de[Dependency Extraction<br>de]
    ba[Bytecode Assembler<br>ba]

    av[Architecture Validation<br>av]
    apk[APK<br>apk]
    tac2bc[TAC2BC<br>tac2bc]

    framework[Framework]

    demos[Demos]
    bp[BugPicker<br>bp]
    hermes[Hermes<br>hermes]

    style common fill:#9cbecc,color:black
    style framework fill:#c0ffc0
    style bp fill:#ffd7cf
    style hermes fill:#ffd7cf

    si --> common

    bi --> common

    br --> si
    br --> bi
    da --> bi

    ifds --> si
    ifds --> br

    ai --> br

    bc --> da

    de --> ai

    tac --> ifds
    tac --> ai

    tac2bc --> tac
    tac2bc --> ba

    apk --> tac

    ba --> ai
    ba --> bc

    av --> de

    framework --> av
    framework --> tac2bc
    
    demos --> framework
    bp --> framework
    hermes --> framework