%%{ init: { 'flowchart': { 'defaultRenderer': 'elk', 'curve': 'linear', 'padding': 10, 'wrappingWidth': 205 } } }%%
flowchart BT
    Framework[Framework<br>framework]
    ThreeAddressCode[Three Address Code<br>tac]
    APK[APK<br>apk]
    DependenciesExtractionLibrary[Dependencies Extraction Library<br>de]
    IDE[IDE<br>ide]
    BytecodeInfrastructure[Bytecode Infrastructure<br>bi]
    AbstractInterpretationFramework[Abstract Interpretation Framework<br>ai]
    Hermes[Hermes<br>hermes]
    ConfigurationExplorer[Configuration Explorer<br>ce]
    Common[Common<br>common]
    BytecodeDisassembler[Bytecode Disassembler<br>da]
    StaticAnalysisInfrastructure[Static Analysis Infrastructure<br>si]
    IFDS[IFDS<br>ifds]
    BytecodeRepresentation[Bytecode Representation<br>br]
    BytecodeAssembler[Bytecode Assembler<br>ba]
    ArchitectureValidation[Architecture Validation<br>av]
    Demos[Demos<br>demos]
    BytecodeCreator[Bytecode Creator<br>bc]

    style Common fill:#9cbecc,color:black
    style Framework fill:#c0ffc0
    style Hermes fill:#ffd7cf

    Framework --> BytecodeAssembler
    Framework --> ArchitectureValidation
    Framework --> ThreeAddressCode
    ThreeAddressCode --> AbstractInterpretationFramework
    ThreeAddressCode --> IFDS
    APK --> ThreeAddressCode
    DependenciesExtractionLibrary --> AbstractInterpretationFramework
    IDE --> StaticAnalysisInfrastructure
    IDE --> BytecodeRepresentation
    BytecodeInfrastructure --> Common
    AbstractInterpretationFramework --> BytecodeRepresentation
    Hermes --> Framework
    ConfigurationExplorer --> BytecodeRepresentation
    BytecodeDisassembler --> BytecodeInfrastructure
    StaticAnalysisInfrastructure --> Common
    IFDS --> IDE
    BytecodeRepresentation --> StaticAnalysisInfrastructure
    BytecodeRepresentation --> BytecodeInfrastructure
    BytecodeAssembler --> BytecodeCreator
    BytecodeAssembler --> AbstractInterpretationFramework
    ArchitectureValidation --> DependenciesExtractionLibrary
    Demos --> Framework
    BytecodeCreator --> BytecodeDisassembler
