/*
 * generated by Xtext
 */
package org.opalj.bdl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BDLRuntimeModule extends org.opalj.bdl.AbstractBDLRuntimeModule {

}
