/*
 * generated by Xtext
 */
package org.opalj.bdl.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.opalj.bdl.services.BDLGrammarAccess;

@SuppressWarnings("all")
public class BDLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected BDLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_ParameterKeyValueElement_ColonKeyword_1_0_or_EqualsSignKeyword_1_1;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (BDLGrammarAccess) access;
		match_ParameterKeyValueElement_ColonKeyword_1_0_or_EqualsSignKeyword_1_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getParameterKeyValueElementAccess().getColonKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getParameterKeyValueElementAccess().getEqualsSignKeyword_1_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if(match_ParameterKeyValueElement_ColonKeyword_1_0_or_EqualsSignKeyword_1_1.equals(syntax))
				emit_ParameterKeyValueElement_ColonKeyword_1_0_or_EqualsSignKeyword_1_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ':' | '='
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID (ambiguity) value=AnyValues
	 */
	protected void emit_ParameterKeyValueElement_ColonKeyword_1_0_or_EqualsSignKeyword_1_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
