/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeTest */

#ifndef _Included_NativeTest
#define _Included_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeTest
 * Method:    nativeFunction
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_NativeTest_nativeFunction
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     NativeTest
 * Method:    foo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_NativeTest_foo
  (JNIEnv *, jobject);

int bar();

#ifdef __cplusplus
}
#endif
#endif
