/* BSD 2-Clause License - see OPAL/LICENSE for details. */
package equals_hashcode.case6;

import equals_hashcode.ContractFulfillment;

/**
 * This class was used to create a class file with some well defined properties. The
 * created class is subsequently used by several tests.
 * 
 * NOTE<br />
 * This class is only meant to be (automatically) compiled by OPAL's build script.
 * 
 * @author Michael Eichberg
 */
@ContractFulfillment(fulfillContract = true, remark = "Default methods generated by Eclipse")
public class NoHashCodeOverrideSuper {

    private int t_super = 42;

    NoHashCodeOverrideSuper(int t) {
        this.t_super = t;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + t_super;
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (!(obj instanceof NoHashCodeOverrideSuper))
            return false;
        NoHashCodeOverrideSuper other = (NoHashCodeOverrideSuper) obj;
        if (t_super != other.t_super)
            return false;
        return true;
    }

}
