/* BSD 2-Clause License - see OPAL/LICENSE for details. */
package equals_hashcode.case7;

import equals_hashcode.ContractFulfillment;

@ContractFulfillment(fulfillContract = true, remark = "Default methods generated by Eclipse")
public class NoHashCodeOverrideNoSuperCheckSuper {

    private int t_super = 42;

    NoHashCodeOverrideNoSuperCheckSuper(int t) {
        this.t_super = t;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + t_super;
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (!(obj instanceof NoHashCodeOverrideNoSuperCheckSuper))
            return false;
        NoHashCodeOverrideNoSuperCheckSuper other = (NoHashCodeOverrideNoSuperCheckSuper) obj;
        if (t_super != other.t_super)
            return false;
        return true;
    }

}
