/*
 * generated by Xtext
 */
package org.opalj.bdl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractBDLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.opalj.bdl.bDL.BDLPackage.eINSTANCE);
		return result;
	}
}
