/*
 * generated by Xtext
 */
package org.opalj.bdl.ui;

import org.eclipse.jface.viewers.ILabelProvider;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.hyperlinking.IHyperlinkHelper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.opalj.bdl.formatting.BDLFormatter;
import org.opalj.bdl.ui.labeling.BDLLabelProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BDLUiModule extends org.opalj.bdl.ui.AbstractBDLUiModule {
	public BDLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration () {
	    return BDLHighlightingConfiguration.class;
	}
	
	public java.lang.Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator(){
		return BDLSemanticHighlightingCalculator.class;
	}
	
	@Override
	public Class<? extends ILabelProvider> bindILabelProvider() {
		return BDLLabelProvider.class;
	}
	
	@Override
	public Class<? extends IHyperlinkHelper> bindIHyperlinkHelper() {
		return BDLHyperLinkHelper.class;
	}
	
	public Class<? extends org.eclipse.xtext.formatting.IFormatter> bindIFormatter() {
		return BDLFormatter.class;
	}
	
}
