/* BSD 2-Clause License - see OPAL/LICENSE for details. */
package org.opalj.ide.problem

/**
 * Interface representing IDE flow functions
 */
trait FlowFunction[Fact <: IDEFact] {
    /**
     * Compute the facts that are generated by this flow function when seeing a fact
     * @param sourceFact the incoming fact
     */
    def compute(sourceFact: Fact): collection.Set[Fact]
}
