/*
 * generated by Xtext
 */
package org.opalj.bdl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.opalj.bdl.services.BDLGrammarAccess;

public class BDLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private BDLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.opalj.bdl.parser.antlr.internal.InternalBDLParser createParser(XtextTokenStream stream) {
		return new org.opalj.bdl.parser.antlr.internal.InternalBDLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public BDLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BDLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
