/* BSD 2-Clause License:
 * Copyright (c) 2009 - 2014
 * Software Technology Group
 * Department of Computer Science
 * Technische Universität Darmstadt
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  - Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  - Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package ai.domain;

/**
 * A class that does perform a large number of operations related to int values.
 * 
 * @author Michael Eichberg
 */
public class IntegerValuesFrenzy {

    static final int theValue = 42;

    // identity function
    static int id(int i) {
        return i;
    }

    // the return value is either i or j
    static int max(int i, int j) {
        if (i < j)
            return i;
        else
            return j;

    }

    // the return value is at most equal to 5
    static int max5(int i) {
        if (i < 5)
            return i;
        else
            return 5;

    }

    // the return value is at most equal to 5; however, to get this result aliases have to
    // be resolved.
    //
    // Code as generated by Eclipse 4.2.1
    // static int aliasingMax5(int i);
    // 0 iload_0 [i]
    // 1 istore_1 [j]
    // 2 iload_1 [j]
    // 3 iconst_5
    // 4 if_icmpge 9
    // 7 iload_0 [i]
    // 8 ireturn
    // 9 iconst_5
    // 10 ireturn
    //
    static int aliasingMax5(int i) {
        int j = i;
        if (j < 5)
            return i;
        else
            return 5;
    }

    static int aliasingMax6(int i) {
        int j = i;
        if (j <= 5)
            return i;
        else
            return 6;
    }

    static int aliasingMinM1(int i) {
        int j = i;
        if (j >= 0)
            return j;
        else
            return -1;
    }

    static int aliasingMin0(int i) {
        int j = i;
        if (j > 0)
            return i;
        else
            return 0;
    }

    static int someSwitch(int i) {
        int j;
        switch (i) {
        case 0:
            j = 0;
            break;
        case 1:
            j = 2;
            break;
        case 2:
            j = 4;
            break;
        default:
            throw new UnknownError();
        }

        return j * i; // j is in the range 0..4 and i in the range 0..2 => result is in
                      // the range [0..8]
    }

    static int someComparisonThatReturns5(int i, int j) {
        if (i == 5 && i == j)
            return j; // returns 5
        else if (j == i && j < 5 && i > 4)
            return -1; // unreachable code
        else
            return 5;
    }

    static int[] array10() {
        int[] is = new int[10];
        for (int i = 0; i <= 10; i++) { // DELIBERATE INDEX OUT OF BOUNDS
            is[i] = i;
        }
        return is;
    }

    private static int getByte() {
        return (int) (System.currentTimeMillis() % 10000);
    }

    // Inspired by:
    // com.sun.xml.internal.org.jvnet.mimepull.BASE64DecoderStream {
    // int decode(byte[] outbuf, int pos, int len) throws IOException
    // }
    static int deadCode(byte[] outbuf, int pos, int len) throws UnknownError {
        int pos0 = pos;
        while (len >= 3) {
            int got = 0;
            while (got < 4) {
                int i = getByte();
                if (i == -1 || i == -2) {
                    boolean atEOF;
                    if (i == -1) {
                        if (got == 0) {
                            return pos - pos0;
                        }
                        atEOF = true; // don't read any more
                    } else { // i == -2
                        if (got == 0) {
                            return pos - pos0;
                        }
                        atEOF = false;
                    }

                    // we cannot reach this point..
                    throw new UnknownError("This is dead code!" + atEOF);
                } else {
                    return -666;
                }
            }
        }
        return 666;
    }

    static void doIt(int i) {
    }

    static int anInt() {
        return (int) Math.random() * 10;
    }

    static void cfDependentValues1_v1() {
        int b = 0;
        int c = 0;
        int i = 0;
        while (i < 2) {
            int a = anInt();
            if (i == 0)
                b = a;
            else
                c = 1; // c is set to "1"
            i++;
        }
        if (c == 0) { // this is dead code... c is always guaranteed to be "1"
            doIt(b);
            doIt(c);
        }
    }

    static void cfDependentValues1_v2() {
        int b = 0;
        int c = 0;
        int i = 0;
        while (i < 2) {
            int a = anInt();
            if (i == 0)
                c = 1; // c is set to "1"
            else
                b = a;
            i++;
        }
        if (c == 0) { // this is dead code... c is always guaranteed to be "1"
            doIt(b);
            doIt(c); 
        }
    }
    
    static void cfDependentValues1_v3() {
        int b = 0;
        int c = 0;
        int i = 0;
        while (i < 2) {
            int a = anInt();
            if (i == 1)
                c = 1; // c is set to "1"
            else
                b = a;
            i++;
        }
        if (c == 0) { // this is dead code... c is always guaranteed to be "1"
            doIt(b);
            doIt(c); 
        }
    }

    static void cfDependentValues2() {
        //
        // The following is basically equivalent to
        // b = anInt
        // c = anInt
        // if(c == 0) {doIt(b);doIt(0)}
        //
        int b = 0;
        int c = 0;
        int i = 0;
        while (i < 2) {
            int a = anInt();
            if (i == 1)
                b = a; // <--- b is the value returned by the second call to anInt
            else
                c = a; // <--- c is the value returned by the first call to anInt
            i++;
        }
        if (c == 0) { // this only constraints "c" and not "b" - though both have the same
                      // origin
            doIt(b); // we know nothing about b here
            doIt(c); // c is "0"
        }
    }

    static void cfDependentValues3() {
        int b = 0;
        int c = 0;
        int i = 0;
        int j = i; // <--- j is just an alias for i
        while (j < 2) {
            int a = anInt();
            if (i == 1)
                b = a;
            else
                c = a;
            i++;
            j = i;
        }
        if (c == 0) { // this only constraints "c" and not "b" - though both have the same
                      // origin
            doIt(b); // we know nothing about b here
            doIt(c); // c is "0"
        }
    }

    static void cfDependentValues4() {
        int b = 0;
        int c = 0;
        int i = 0;
        int j = i; // j is just an alias for i
        while (j < 2) {
            int a = anInt();
            if (i == 1)
                b = a;
            else
                c = a;
            i++;
            j = i;
        }
        if (i == 2) {
            doIt(j); // j == 2
            doIt(b); // some value (but not "c")
            doIt(c); // some value (but not "b")
        }
    }

    static void cfDependentValues5() {
        int b = 0;
        int c = 0;
        int i = 0;
        int j = i; // j is just an alias for i
        while (j < 2) {
            int a = anInt();
            if (a == 1)
                b = a; // <--- the value depends on a
            else
                c = a; // <--- the value depends on a
            i++;
            j = i;
        }
        // b and c may refer to the same value or different values
        if (i == 2) {
            doIt(j); // j is "2"
            doIt(b); // b is either "0" or "1"
            doIt(c);
        }
    }
}
