/*
 * generated by Xtext
 */
package org.opalj.bdl.ui.contentassist

import org.opalj.bdl.ui.contentassist.AbstractBDLProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class BDLProposalProvider extends AbstractBDLProposalProvider {
}
