/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeTest */

#ifndef _Included_NativeTest
#define _Included_NativeTest
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_NativeTest_f1(JNIEnv *env, jobject obj, jint a, jint b);

JNIEXPORT int JNICALL Java_NativeTest_f2(JNIEnv *env, jobject obj);

JNIEXPORT int JNICALL Java_NativeTest_f3(JNIEnv *env, jobject obj, jint a);

JNIEXPORT int JNICALL Java_NativeTest_f4(JNIEnv *env, jobject obj, jint a);

JNIEXPORT int JNICALL Java_NativeTest_f5(JNIEnv *env, jobject obj, jint a, jint b);

int source();

void sink(int num);

int sanitize(int num);

#ifdef __cplusplus
}
#endif
#endif
