/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TaintTest */

#ifndef _Included_TaintTest
#define _Included_TaintTest
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_TaintTest_sum(JNIEnv *env, jobject obj, jint a, jint b);

JNIEXPORT int JNICALL Java_TaintTest_propagate_1source(JNIEnv *env, jobject obj);

JNIEXPORT int JNICALL Java_TaintTest_propagate_1sanitize(JNIEnv *env, jobject obj, jint a);

JNIEXPORT int JNICALL Java_TaintTest_propagate_1sink(JNIEnv *env, jobject obj, jint a);

JNIEXPORT int JNICALL Java_TaintTest_sanitize_1only_1a_1into_1sink(JNIEnv *env, jobject obj, jint a, jint b);

JNIEXPORT void JNICALL Java_TaintTest_propagate_1identity_1to_1sink(JNIEnv *env, jobject obj, jint a);

JNIEXPORT void JNICALL Java_TaintTest_propagate_1zero_1to_1sink(JNIEnv *env, jobject obj, jint a);

int identity(int a);

int zero(int a);

int source();

void sink(int num);

int sanitize(int num);

#ifdef __cplusplus
}
#endif
#endif
