/* BSD 2-Clause License - see OPAL/LICENSE for details. */
package equals_hashcode.case8;

import equals_hashcode.ContractFulfillment;

/**
 * This class was used to create a class file with some well defined properties. The
 * created class is subsequently used by several tests.
 * 
 * NOTE<br />
 * This class is only meant to be (automatically) compiled by OPAL's build script.
 * 
 * @author Michael Eichberg
 */
@ContractFulfillment(fulfillContract = true, remark = "Based on default methods generated by Eclipse, with a transitive field access in hashCode()")
public class TransitiveAccessInHashCode {

    private boolean something;

    private boolean calculateSomething() {
        return something;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + (calculateSomething() ? 1231 : 1237);
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (!(obj instanceof TransitiveAccessInHashCode))
            return false;
        TransitiveAccessInHashCode other = (TransitiveAccessInHashCode) obj;
        if (something != other.something)
            return false;
        return true;
    }

}
